Update .config/scripts/bac

diff --git a/dot_config/scripts/executable_bac b/dot_config/scripts/executable_bac
--- a/dot_config/scripts/executable_bac
+++ b/dot_config/scripts/executable_bac
@@ -100,11 +100,11 @@ backup_configs() {
   # Remove and back up cache dirs
   for cache_dir in "${cache_dirs[@]}"; do
     # Replace config_dir with chezmoi_dir string
-    chezmoi_cache_dir="${cache_dir/$CONFIG_DIR/$CHEZMOI_CACHE_DIR}"
+    chezmoi_cache_dir="${cache_dir/$CACHE_DIR/$CHEZMOI_CACHE_DIR}"
     echo "🗑️ Removing $chezmoi_cache_dir..."
     rm -rf "$chezmoi_cache_dir" || echo "⚠️ Failed to remove $chezmoi_cache_dir"
     echo "💾 Backing up $config_dir..."
-    chezmoi add "$config_dir" || echo "⚠️ Failed to back up $config_dir"
+    chezmoi add "$cache_dir" || echo "⚠️ Failed to back up $cache_dir"
     echo "=============================================================================================================================================================================="
   done
 
