Update .config/scripts/bac

diff --git a/dot_config/scripts/executable_bac b/dot_config/scripts/executable_bac
--- a/dot_config/scripts/executable_bac
+++ b/dot_config/scripts/executable_bac
@@ -4,7 +4,8 @@ set -euo pipefail
 
 CONFIG_DIR="$HOME/.config"
 CACHE_DIR="$HOME/.cache"
-CHEZMOI_DIR="$HOME/.local/share/chezmoi/dot_config"
+CHEZMOI_CONFIG_DIR="$HOME/.local/share/chezmoi/dot_config"
+CHEZMOI_CACHE_DIR="$HOME/.local/share/chezmoi/dot_cache"
 
 backup_packages() {
   echo "📦 Backing up packages..."
@@ -75,20 +76,35 @@ backup_configs() {
     "$CONFIG_DIR/fastfetch"
   )
 
+  declare -a cache_dirs=(
+    "$CACHE_DIR"/wal
+  )
+
   # Prompt for wallpapers directory
   read -p "Re-add ~/.config/wallpapers? [y/N] " answer
   if [[ "$answer" =~ ^[Yy]$ ]]; then
     config_dirs+=("$CONFIG_DIR/wallpapers")
   fi
 
-  # Remove and back up directories in a single loop
-  for dir in "${config_dirs[@]}"; do
+  # Remove and back up config dirs
+  for config_dir in "${config_dirs[@]}"; do
     # Replace config_dir with chezmoi_dir string
-    chezmoi_dir="${dir/$CONFIG_DIR/$CHEZMOI_DIR}"
-    echo "🗑️ Removing $chezmoi_dir..."
-    rm -rf "$chezmoi_dir" || echo "⚠️ Failed to remove $chezmoi_dir"
-    echo "💾 Backing up $dir..."
-    chezmoi add "$dir" || echo "⚠️ Failed to back up $dir"
+    chezmoi_config_dir="${config_dir/$CONFIG_DIR/$CHEZMOI_CONFIG_DIR}"
+    echo "🗑️ Removing $chezmoi_config_dir..."
+    rm -rf "$chezmoi_config_dir" || echo "⚠️ Failed to remove $chezmoi_config_dir"
+    echo "💾 Backing up $config_dir..."
+    chezmoi add "$config_dir" || echo "⚠️ Failed to back up $config_dir"
+    echo "=============================================================================================================================================================================="
+  done
+
+  # Remove and back up cache dirs
+  for cache_dir in "${cache_dirs[@]}"; do
+    # Replace config_dir with chezmoi_dir string
+    chezmoi_cache_dir="${cache_dir/$CONFIG_DIR/$CHEZMOI_CACHE_DIR}"
+    echo "🗑️ Removing $chezmoi_cache_dir..."
+    rm -rf "$chezmoi_cache_dir" || echo "⚠️ Failed to remove $chezmoi_cache_dir"
+    echo "💾 Backing up $config_dir..."
+    chezmoi add "$config_dir" || echo "⚠️ Failed to back up $config_dir"
     echo "=============================================================================================================================================================================="
   done
 
